### ISSUE TITLE
How to use own files (FEA result file format)?

### ISSUE THREAD

**Issue by moorjuli** [GuoxinFang/ReinforcedFDM#1]
I was able to run the example .tet files succesfully and then tried to work with own 3D models. Sadly I couldn't find any information on the .tet file format and was not able to create a working .tet or .obj file out of one of my 3d models. Maybe you could add/provide some information on the correct file format and on how to create those files? That would be very helpful for me.
Thank you for your amazing work!

**Comment by guruaathavanalu** [comment]
@moorjuli  were you able to generate your .tet file?

**Comment by moorjuli** [comment]
Hi @guruaathavanalu,
Using [TetGen](https://wias-berlin.de/software/tetgen/) I was able to generate a tetrahedral mesh from a .stl file in .mesh format. Then I used a python library called [Mouette](https://github.com/GCoiffier/mouette/), which is able to convert from .mesh to .tet file format. The generated .tet file then can be loaded into ReinforcedFDM. Next step will be to run FEM analysis on own parts, to also get their results into the software.

**Comment by guruaathavanalu** [comment]
Hello @moorjuli ,
Thanks for the reply, I was so confused about the .tet file, finally wrote a parser for converting the mesh file to .tet. I am now stuck with the FEM analysis part. The file (Model/ FEM_Selection_file/bunnyhead.txt) they use has the tetrahedron index and 7 other values. How do you generate this file and what are those components?

**Comment by moorjuli** [comment]
I think that these values are the results of the FEM analysis in some format, but at the moment I am stuck there as well. I started by using the function "Export tetrahedal mesh to Abaqus INP file" you find in the Function dropdown. The .inp file can be loaded into abaqus, but I do not know what to do with it yet. Let me know if you find out something @guruaathavanalu 😄

**Comment by guruaathavanalu** [comment]
Sure thing @moorjuli; @GuoxinFang  could you maybe shed light on what are those seven components of stress in the FEM Analysis file? It would be of great help to us. Thanks

**Comment by moorjuli** [comment]
This is all the information on this I found in the Paper
> Given user-specified loads on the model H, we use commercial FEA software (e.g. Abaqus) to compute the stress distribution and output the 3 × 3 stress tensor 𝜎(𝑒) for every tetrahedral element 𝑒 ∈ T at the centers x𝑒. 

I tried to use Abaqus, but I am stuck exporting the result in the correct format. Any Ideas/any Abaqus experts here?

**Comment by moorjuli** [comment]
Hey @guruaathavanalu,
happy to tell you, I made some progress and that I was able to create working fea result files. I found out that the values 2-7 are stress values, that can be exported with Abaqus CAE. I still don't know what the last value is, but it seems that it can be ignored and is not used by the software at all. If you need a detailed description on how to export the values, please tell me, so I can help you with that.

**Comment by guruaathavanalu** [comment]
Hey @moorjuli ,
 That is soo good to hear, it would be great if could explain how you did it.
Thanks

**Comment by moorjuli** [comment]
- Okay so first I created my .tet file as described above. 

- Then I used the "Export to Abaqus" function to generate an .inp file. I imported the file into Abaqus (There is a limited Student Version available for free and it should also be possible to use a different FEA software) and ran a simple FEA analysis. There are many tutorials on this, that can explain that step way better. 
- To output the right data, open the simulation results in Abaqus and from the main menu (at the top) select Report and then Field Output. Select Centroid as the Position. Then select the 6 stress components. 
- In the output file, you will then find the indicies and the six stress values. I simply used a text editor to transform that data into the right format. Save as .txt with the same name then the .tet file. 
- You should be able to read the .tet file and load the FEA results. 

You can also take a look at [S3 DeformFDM](https://github.com/zhangty019/S3_DeformFDM), which is a further developed project on a very similar basis, that also integrates the ReinforcedFDM approach. It worked a little better for me and also integrates the manufacturing part (gcode generation, etc.), even though I needed to do some code adjustments. Feel free to contact me if you have any further questions @guruaathavanalu

**Comment by guruaathavanalu** [comment]
Thank you so much for the detailed explanation @moorjuli
